config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about', to: "about#index", as: :about

  get "sign_up", to: "registrations#new"

  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"

  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  root to: 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :variants, class_name: 'ProductVariant'
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token) do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quatity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)

    order_item = order.items.find_or_initialize_by(
      product_id: product_id
    )

    order_item.price = product.price
    order_item.quatity = quantity

    order_item.save
  end

  def remove_item(id:)
    order.items.destroy(id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user


  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  before_action :current_cart

  # this allows carts to be filled with the corrent products.
  def current_cart
    @current_cart ||= ShoppingCart.new(token: cart_token)
  end
  helper_method :current_cart

  private

  def cart_token
    return @cart_token unless @cart_token.nil?

    session[:cart_token] ||= SecureRandom.hex(8)
    @cart_token = session[:cart_token]
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

# this is joining all categories to products categories.
  def index
    @categories = Category.joins(:products).select('categories.*, count(products.id) as products_count').group('categories.id').order(:title)
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  # this controls saving product to cart and deleting product from cart.
  def index
    @items = current_cart.order.items
  end

  def create
    current_cart.add_item(
      product_id: params[:product_id],
      quantity: params[:quantity]
    )

    redirect_to cart_path
  end

  def destroy
    current_cart.remove_item(id: params[:id])
    redirect_to cart_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # this allows user to see categories and their products.
  def index
      @category = Category.find(params[:category_id])
      @products = @category.products.includes(:variants).order(:title)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController


  # this allows users to be created
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:fullname, :email, :password, :password_confirmation, :dob, :state)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # this allows users to log in and log out.
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in succesfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/views/categories/index.html.erb
<!-- Main page that shows all categories for the products we sell. -->
<div class="d-flex align-items-center justify-content-center">
<h1>Categories (<%= @categories.length %>)</h1>
</div>

<div class="d-flex align-items-center justify-content-center">
<ol>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category_products_path(category) do %>
        <%= category.title %>
        (<%= category.products_count %> products)
      <% end %>
    </li>
  <% end %>
</ol>
</div>


<div class="d-flex align-items-center justify-content-center">
  <h1>Restrictions</h1>
</div>
<ul>
  <%= STATES %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Joshua's 28H Coding Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>

    <!-- navbar for application.  Render wasn't working for some odd reason. -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link" %>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if Current.user  %>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", sign_up_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", sign_in_path, class: "nav-link"%>
          </li>
          <% end %>
        </ul>

        </div>
      </div>
    </nav>


      <!-- again having trouble rendering flash notices so just put it in  this file for now. -->
      <div class="container">
        <% if flash[:notice] %>
          <div class="alert alert-info mt-4" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>

        <% if flash[:alert] %>
          <div class="alert alert-warning mt-4" role="alert">
            <%= flash[:alert] %>
          </div>
        <% end %>
        <%= yield %>
      </div>

  </body>
</html>

app/views/order_items/index.html.erb
<!-- This is showing all of your saved Products. -->
<h2>Current Cart</h2>


<table>
  <thead>
    <tr>
      <td>Product</td>
      <td>Price</td>
      <td>Quantity</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product.title %></td>
        <td><%= number_to_currency item.price %></td>
        <td><%= item.quatity %></td>
        <td>
          <%= form_for item, method: :delete do |f| %>
            <%= f.submit "Remove" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/index.html.erb
<h2>
  <%= link_to "Categories", root_path %> /
  <%= @category.title %> /
  Products
</h2>

<!-- Show all products that belong to the category -->
<ol>
  <% @products.each do |product| %>
    <li>
      <%= product.title %> (<%= number_to_currency product.price %>)

      <%= form_tag order_items_path do %>
        <%= hidden_field_tag :product_id, product.id %>
        <%= number_field_tag :quantity, 1 %>
        <%= submit_tag "Add to Cart" %>
      <% end %>


      <ul>
        <% product.variants.each do |variant| %>
          <li><%= variant.title %> (<%= number_to_currency variant.price %>)</li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>